import { useState } from "react";
import { styles } from "./Home.styles.ts";
import { FormField } from "../FormField/FormField.tsx";
import { CircularProgress } from "@mui/material";

export const Home = () => {
  const [loading, setLoading] = useState(false);
  // const [allPosts, setAllPosts] = useState(null);
  const [searchText, setSearchText] = useState("dsa");
  console.log(setLoading(true),setSearchText('s'));
  const classes = styles();

  return (
    <div css={classes.container}>
      <h1 css={classes.title}>The Community Showcase</h1>
      <p css={classes.subTitle}>
        Browse through a collection of imaginative and visually stunning images
        generated by DALL-E AI
      </p>
      <FormField />
      <div css={classes.loaderWrapper}>
        {loading ? (
          <CircularProgress />
        ) : (
          <>
            {searchText && (
              <h1 css={classes.titleSearch}>
                Showing result for <span css={classes.subtitleSearch}>{searchText}</span>
              </h1>
            )}
          </>
        )}
      </div>
    </div>
  );
};
